# Copyright 2025 ISP RAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

ARG BASE_IMAGE="sydr/ubuntu22.04-sydr-fuzz"
FROM $BASE_IMAGE

ARG SYDR_ARCHIVE="./sydr.zip"

WORKDIR /

# Only for libhtp-rs.
RUN rustup override set nightly-2025-05-01
RUN cargo afl config --build

RUN git clone https://github.com/cccs-rtmorti/libhtp-rs.git

WORKDIR /libhtp-rs

# Checkout specified commit. It could be updated later.
RUN git checkout 2bef6f30c916fdd057a15434466ea432b0bbf17c

RUN mkdir /corpus && cp /libhtp-rs/tests/files/*.t /corpus

RUN mkdir -p /libhtp-rs/libafl_difuzz/targets
COPY sydr_and_cover/targets/sydr_htp.rs /libhtp-rs/libafl_difuzz/targets
COPY sydr_and_cover/Cargo.toml /libhtp-rs/libafl_difuzz

# Copy LibAFL-DiFuzz target template.
COPY directed_target /directed_target

WORKDIR /directed_target

# Build libhtp-rs for LibAFL-DiFuzz.
ADD ${SYDR_ARCHIVE} ./
RUN unzip -o ${SYDR_ARCHIVE} && rm ${SYDR_ARCHIVE}
RUN OUT_DIR=/ cargo make all

WORKDIR /

# Set SYDR_LLVM_COV env.
ENV SYDR_LLVM_COV=/usr/bin/llvm-cov-20
