exit-on-time = 7200

[sydr]
args = "--wait-jobs -s 90 -j2"
target = "/result/fuzz/sydr/fuzz-dwfl-core @@"
jobs = 2

[difuzz]
path = "/sydr-fuzz/sydr/difuzz/libafl_difuzz"
target = "/result/fuzz/difuzz/dwfl-core/difuzz_target_dwfl-core @@"
args = "-j4 -l64 -i /result/fuzz/corpus -e /result/fuzz/difuzz/dwfl-core/ets.toml"
casr_bin = "/result/fuzz/difuzz/dwfl-core/casr_dwfl-core"

[cov]
target = "/result/fuzz/cov/fuzz-dwfl-core @@"
