exit-on-time = 7200

[sydr]
args = "--wait-jobs -s 90 -j2"
target = "/result/fuzz/sydr/fuzz-libdwfl @@"
jobs = 2

[libfuzzer]
path = "/result/fuzz/libfuzzer/fuzz-libdwfl"
args = "-jobs=1000 -workers=4 /result/fuzz/corpus"

[cov]
target = "/result/fuzz/cov/fuzz-libdwfl @@"
