exit-on-time = 7200

[sydr]
args = "--wait-jobs -s 90 -j2"
target = "/result/fuzz/sydr/fuzz-libelf @@"
jobs = 2

[aflplusplus]
target = "/result/fuzz/aflpp/fuzz-libelf @@"
args = "-i /result/fuzz/corpus"
jobs = 4

[cov]
target = "/result/fuzz/cov/fuzz-libelf @@"
