[sydr]
args = "--invert-n 2048 -l debug --app-timeout 300 --solving-timeout 30"
target = "/transform_combined_jpeg_sydr @@"
jobs = 2

[libfuzzer]
path = "/transform_combined_jpeg_fuzzer"
args = "-rss_limit_mb=16384 -jobs=10 -workers=2 /fuzz/corpus"

