# Copyright 2025 ISP RAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

ARG BASE_IMAGE=""
FROM $BASE_IMAGE

WORKDIR /

# Clone target from GitHub.
RUN git clone https://git.code.sf.net/p/giflib/code giflib-bugs-74

WORKDIR /giflib-bugs-74

# Checkout specified commit. It could be updated later.
RUN git checkout 72e31ff && git submodule update --init --recursive

# Copy LibAFL-DiFuzz target template.
COPY directed_target /directed_target

WORKDIR /directed_target

# Build giflib for LibAFL-DiFuzz.
RUN OUT_DIR=/ cargo make all

# Prepare seed corpus.
RUN mkdir /corpus; echo "GIF" > /corpus/in
