[sydr]
args = "--wait-jobs"
target = "/instance_enumerate_fuzzer_split_input_sydr @@"
jobs = 2

[libfuzzer]
path = "/instance_enumerate_fuzzer_split_input"
args = "-close_fd_mask=3 /corpus/"
cmin = false

[cov]
target = "/instance_enumerate_fuzzer_split_input_cov @@"