# Copyright 2025 ISP RAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

ARG BASE_IMAGE="sydr/ubuntu22.04-sydr-fuzz"
FROM $BASE_IMAGE

ARG SYDR_ARCHIVE="./sydr.zip"

WORKDIR /

# Clone Ollama.
RUN git clone https://github.com/ollama/ollama.git /ollama

WORKDIR /ollama

RUN git checkout 26214125e86ac1d4512dff68c983137589cfddbf

# Apply patch.
COPY ollama.patch build.sh ./
RUN git apply ollama.patch

# Extract corpuses.
COPY corpus.zip /
RUN unzip /corpus.zip -d /

# Create directories for fuzz targets.
RUN mkdir sydr && cd sydr && mkdir -p convert/tokenizer convert/vocabulary \
    model/encode model/decode parser/parsefile server/newlayer server/manifest \
    thinking/state thinking/eat thinking/content

# Move fuzz targets.
RUN mkdir fuzz
COPY fuzz.go fuzz

COPY thinking_state_sydr.go sydr/thinking/state/main.go
COPY thinking_eat_sydr.go sydr/thinking/eat/main.go
COPY thinking_content_sydr.go sydr/thinking/content/main.go
COPY server_newlayer_sydr.go sydr/server/newlayer/main.go
COPY server_manifest_sydr.go sydr/server/manifest/main.go
COPY parser_parsefile_sydr.go sydr/parser/parsefile/main.go
COPY model_encode_sydr.go sydr/model/encode/main.go
COPY model_decode_sydr.go sydr/model/decode/main.go
COPY convert_tokenizer_sydr.go sydr/convert/tokenizer/main.go
COPY convert_vocabulary_sydr.go sydr/convert/vocabulary/main.go

# Build GGML.
RUN mkdir -p build && cd build && \
    CC=clang-18 CXX=clang++-18 cmake --preset 'CPU' -DGGML_AVX_VNNI=OFF .. && \
    make -j

# Copy LibAFL-DiFuzz target template.
COPY directed_target /directed_target

WORKDIR /directed_target

# Build image for LibAFL-DiFuzz.
ADD ${SYDR_ARCHIVE} ./
RUN unzip -o ${SYDR_ARCHIVE} && rm ${SYDR_ARCHIVE}
RUN OUT_DIR=/ cargo make all

WORKDIR /
