# Copyright 2025 ISP RAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

ARG BASE_IMAGE="sydr/ubuntu22.04-sydr-fuzz"
FROM $BASE_IMAGE

ARG SYDR_ARCHIVE="./sydr.zip"

WORKDIR /

RUN git clone https://github.com/golang/image.git
RUN git clone --depth=1 https://github.com/dvyukov/go-fuzz-corpus.git

WORKDIR /image

RUN git checkout c574db581976698ac047466629eeeb7b17bb49dd

RUN go get github.com/dvyukov/go-fuzz/go-fuzz-dep

COPY fuzz.go ./

# Move target and additional libs to main project.
RUN cp -r /root/.go/src/image/png . && \
    cp -r /root/.go/src/image/jpeg . && \
    cp -r /root/.go/src/image/gif . && \
    cp -r /root/.go/src/internal/byteorder . && \
    cp -r /root/.go/src/image/internal/imageutil .

RUN mkdir cmd/webp && \
    mkdir cmd/tiff && \
    mkdir cmd/png && \
    mkdir cmd/jpeg && \
    mkdir cmd/gif

COPY sydr_webp.go cmd/webp/main.go
COPY sydr_tiff.go cmd/tiff/main.go
COPY sydr_png.go cmd/png/main.go
COPY sydr_jpeg.go cmd/jpeg/main.go
COPY sydr_gif.go cmd/gif/main.go

# RUN sed -i '238ipanic("reached TP")' /image/gif/reader.go
# RUN sed -i '350ipanic("reached TP")' /image/gif/reader.go
RUN sed -i '404ipanic("reached TP")' /image/gif/reader.go

RUN sed -i '228ipanic("reached TP")' /image/jpeg/reader.go
RUN sed -i '330ipanic("reached TP")' /image/jpeg/reader.go
RUN sed -i '763ipanic("reached TP")' /image/jpeg/reader.go

RUN sed -i '174ipanic("reached TP")' /image/png/reader.go
RUN sed -i '611ipanic("reached TP")' /image/png/reader.go
# RUN sed -i '877ipanic("reached TP")' /image/png/reader.go
RUN sed -i '939ipanic("reached TP")' /image/png/reader.go

RUN sed -i '72ipanic("reached TP")' /image/tiff/reader.go
RUN sed -i '393ipanic("reached TP")' /image/tiff/reader.go
# RUN sed -i '486ipanic("reached TP")' /image/tiff/reader.go
RUN sed -i '689ipanic("reached TP")' /image/tiff/reader.go

RUN sed -i '175ipanic("reached TP")' /image/webp/decode.go
RUN sed -i '211ipanic("reached TP")' /image/webp/decode.go

# Copy LibAFL-DiFuzz target template.
COPY directed_target /directed_target

WORKDIR /directed_target

# Build image for LibAFL-DiFuzz.
ADD ${SYDR_ARCHIVE} ./
RUN unzip -o ${SYDR_ARCHIVE} && rm ${SYDR_ARCHIVE}
RUN OUT_DIR=/ cargo make all

WORKDIR /
