# Copyright 2025 ISP RAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

ARG BASE_IMAGE=""
FROM $BASE_IMAGE

WORKDIR /

# Clone target from GitHub.
RUN git clone https://gitlab.gnome.org/GNOME/libxml2.git libxml2_ef709ce2

WORKDIR /libxml2_ef709ce2

RUN git checkout ef709ce2 && git submodule update --init --recursive
COPY patch /
RUN git apply /patch

# Copy LibAFL-DiFuzz target template.
COPY directed_target /directed_target

WORKDIR /directed_target

# Build libxml for LibAFL-DiFuzz.
RUN OUT_DIR=/ cargo make all

# Prepare seed corpus.
RUN mkdir /corpus; cp -r /libxml2_ef709ce2/test/dtd* /corpus; cp -r /libxml2_ef709ce2/test/dtds/* /corpus; rm /corpus/dtd1
