# Copyright 2025 ISP RAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

ARG BASE_IMAGE="sydr/ubuntu22.04-sydr-fuzz"
FROM $BASE_IMAGE

ARG SYDR_ARCHIVE="./sydr.zip"

WORKDIR /

# Only for goblin.
RUN rustup override set nightly-2025-05-01

# Clone target from GitHub.
RUN git clone https://github.com/m4b/goblin.git

WORKDIR /goblin

# Checkout specified commit. It could be updated later.
RUN git checkout 83ce901e27dd801d44a78108041bdd7a8efd378c

RUN sed -i '129ipanic!("reached TP");' /goblin/src/archive/mod.rs
RUN sed -i '168ipanic!("reached TP");' /goblin/src/archive/mod.rs
RUN sed -i '344ipanic!("reached TP");' /goblin/src/archive/mod.rs

RUN sed -i '163ipanic!("reached TP");' /goblin/src/elf/mod.rs
RUN sed -i '270ipanic!("reached TP");' /goblin/src/elf/mod.rs
RUN sed -i '367ipanic!("reached TP");' /goblin/src/elf/mod.rs

RUN sed -i '157ipanic!("reached TP");' /goblin/src/mach/mod.rs
RUN sed -i '188ipanic!("reached TP");' /goblin/src/mach/mod.rs
RUN sed -i '247ipanic!("reached TP");' /goblin/src/mach/mod.rs

RUN sed -i '100ipanic!("reached TP");' /goblin/src/pe/mod.rs
RUN sed -i '168ipanic!("reached TP");' /goblin/src/pe/mod.rs

RUN sed -i '172ipanic!("reached TP");' /goblin/src/pe/debug.rs

COPY build-config/Cargo.toml fuzz/

COPY sydr_*.rs fuzz/fuzz_targets/

# Copy LibAFL-DiFuzz target template.
COPY directed_target /directed_target

WORKDIR /directed_target

# Build goblin for LibAFL-DiFuzz.
ADD ${SYDR_ARCHIVE} ./
RUN unzip -o ${SYDR_ARCHIVE} && rm ${SYDR_ARCHIVE}
RUN OUT_DIR=/ cargo make all

WORKDIR /

# Create corpus.
RUN git clone https://github.com/JonathanSalwan/binary-samples /corpus && \
rm -rf /corpus/anti-disassembler && rm /corpus/MIT_LICENSE && rm /corpus/README.md

# Set SYDR_LLVM_COV env.
ENV SYDR_LLVM_COV=/usr/bin/llvm-cov-20
