# Copyright 2026 ISP RAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

# Variables
[env]
PROJECT_DIR = { script = ["pwd"], condition = { env_not_set = ["PROJECT_DIR"] } }
EXAMPLE_DIR = { value = "/result/elfutils" }
DIFUZZ_DIR = { value = "/directed_target/sydr/difuzz", condition = { env_not_set = ["DIFUZZ_DIR"] } }
DIFUZZ_DIR_ABS = { script = ["realpath ${DIFUZZ_DIR}"] }
DIFUZZ_LLVM_VERSION = { script = ['version="$(LC_ALL=C readelf -d "${DIFUZZ_DIR_ABS}/difuzz" 2>/dev/null | sed -nE "s/.*NEEDED.*\[libLLVM(-|\.so\.)([0-9]+)[^]]*\].*/\2/p" | sort -u)"; case "${version}" in 18|21) printf "%s\n" "${version}" ;; *) echo "Cannot detect a supported LLVM version from ${DIFUZZ_DIR_ABS}/difuzz" >&2; exit 1 ;; esac'] }
DIFUZZ_LLVM_BINDIR = { script = ["llvm-config-${DIFUZZ_LLVM_VERSION} --bindir"] }
OUT_DIR = { value = "${PROJECT_DIR}", condition = { env_not_set = ["OUT_DIR"] } }
OUT_DIR_ABS = { script = ["realpath ${OUT_DIR}"] }
DIFUZZ_ICACHE_ARG = { script = ['if [ -n "${DIFUZZ_ICACHE}" ]; then printf %s "--icache ${DIFUZZ_ICACHE}"; else printf %s ""; fi'] }
DIFUZZ_ARGS = { value = "-r main --weights reverse -o difuzz -j8 --analyse-icalls strong ${DIFUZZ_ICACHE_ARG}", condition = { env_not_set = ["DIFUZZ_ARGS"] } }
CARGO_TARGET_DIR = { value = "target", condition = { env_not_set = [
  "CARGO_TARGET_DIR",
] } }
PROFILE = { value = "release", condition = { env_not_set = ["PROFILE"] } }
LIBAFL_CC = '${DIFUZZ_DIR_ABS}/libafl_cc'
LIBAFL_CXX = '${DIFUZZ_DIR_ABS}/libafl_cxx'
FUZZER = '${DIFUZZ_DIR_ABS}/libafl_difuzz'
ETS_SHARED_MANAGER = '${DIFUZZ_DIR_ABS}/ETSSharedManager'
TARGET = '${OUT_DIR_ABS}/difuzz_target_dwfl-core'

[tasks.unsupported]
script_runner = "@shell"
script = '''
echo "Cargo-make not integrated yet on this"
'''

[tasks.debug]
linux_alias = "debug_unix"
mac_alias = "debug_unix"
windows_alias = "unsupported"

[tasks.debug_unix]
script_runner = "@shell"
script = '''
cd ${PROJECT_DIR}
export CC=${DIFUZZ_LLVM_BINDIR}/clang
export CXX=${DIFUZZ_LLVM_BINDIR}/clang++
OUT=$EXAMPLE_DIR $BUILD_SH dwfl-core $EXAMPLE_DIR 0
mv ${EXAMPLE_DIR}/fuzz-dwfl-core ${OUT_DIR_ABS}/debug_dwfl-core
'''

[tasks.casr]
linux_alias = "casr_unix"
mac_alias = "casr_unix"
windows_alias = "unsupported"

[tasks.casr_unix]
script_runner = "@shell"
script = '''
cd ${PROJECT_DIR}
export CC=${DIFUZZ_LLVM_BINDIR}/clang
export CXX=${DIFUZZ_LLVM_BINDIR}/clang++
append_flags="-fsanitize=address,integer,bounds,null,undefined,float-divide-by-zero"
export CFLAGS="$CFLAGS $append_flags"
export CXXFLAGS="$CXXFLAGS $append_flags"

OUT=$EXAMPLE_DIR $BUILD_SH dwfl-core $EXAMPLE_DIR 0
mv ${EXAMPLE_DIR}/./fuzz-dwfl-core ${OUT_DIR_ABS}/casr_dwfl-core
'''

[tasks.coverage]
linux_alias = "coverage_unix"
mac_alias = "coverage_unix"
windows_alias = "unsupported"

[tasks.coverage_unix]
script_runner = "@shell"
script = '''
cd ${PROJECT_DIR}
export CC=${DIFUZZ_LLVM_BINDIR}/clang
export CXX=${DIFUZZ_LLVM_BINDIR}/clang++
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py --sig -a insert -l c -f ${EXAMPLE_DIR}/fuzz-main.c

append_flags="-g -fprofile-instr-generate -fcoverage-mapping"
export CFLAGS="$CFLAGS $append_flags"
export CXXFLAGS="$CXXLAGS $append_flags"

OUT=$EXAMPLE_DIR $BUILD_SH dwfl-core $EXAMPLE_DIR 0

python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py --sig -a remove -l c -f ${EXAMPLE_DIR}/fuzz-main.c
mv ${EXAMPLE_DIR}/./fuzz-dwfl-core ${OUT_DIR_ABS}/coverage_dwfl-core
'''

[tasks.difuzz]
linux_alias = "difuzz_unix"
mac_alias = "difuzz_unix"
windows_alias = "unsupported"

[tasks.difuzz_unix]
script_runner = "@shell"
script = '''
cd ${PROJECT_DIR}
export LLVM_COMPILER=clang
export LLVM_COMPILER_PATH=${DIFUZZ_LLVM_BINDIR}
export CC=wllvm; export CXX=wllvm++

python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a insert -l c -f ${EXAMPLE_DIR}/fuzz-main.c
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a comment -l c -f ${EXAMPLE_DIR}/fuzz-main.c
OUT=$EXAMPLE_DIR $BUILD_SH dwfl-core $EXAMPLE_DIR 0
cd ${OUT_DIR_ABS}
${DIFUZZ_DIR_ABS}/difuzz -c ${PROJECT_DIR}/config.toml -b ${EXAMPLE_DIR}/./fuzz-dwfl-core -e ${OUT_DIR_ABS}/ets.toml ${DIFUZZ_ARGS}
'''

[tasks.target]
linux_alias = "target_unix"
mac_alias = "target_unix"
windows_alias = "unsupported"

[tasks.target_unix]
script_runner = "@shell"
script = '''
cd ${PROJECT_DIR}
export CC=${LIBAFL_CC}
export CXX=${LIBAFL_CXX}
export LIBAFL_SHARED_NAME="dwfl-core"
${ETS_SHARED_MANAGER} -a remove -n ${LIBAFL_SHARED_NAME}
${ETS_SHARED_MANAGER} -a create -n ${LIBAFL_SHARED_NAME}
${ETS_SHARED_MANAGER} -a parse -n ${LIBAFL_SHARED_NAME} -i ${OUT_DIR_ABS}/ets.toml
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a uncomment -l c -f ${EXAMPLE_DIR}/fuzz-main.c
OUT=$EXAMPLE_DIR $BUILD_SH dwfl-core $EXAMPLE_DIR 0
${ETS_SHARED_MANAGER} -a dump -n ${LIBAFL_SHARED_NAME} -o ${OUT_DIR_ABS}/ets.toml
${ETS_SHARED_MANAGER} -a remove -n ${LIBAFL_SHARED_NAME}
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a remove -l c -f ${EXAMPLE_DIR}/fuzz-main.c
mv ${EXAMPLE_DIR}/./fuzz-dwfl-core ${TARGET}
'''
dependencies = ["difuzz"]

# Run the fuzzer
[tasks.run]
linux_alias = "run_unix"
mac_alias = "run_unix"
windows_alias = "unsupported"

[tasks.run_unix]
script_runner = "@shell"
script = '''
LIBAFL_DEBUG_OUTPUT=1 ${FUZZER} -- ${TARGET} -- @@
'''
dependencies = ["target"]

# Clean all built artifacts
[tasks.cleanall]
script_runner = "@shell"
script = '''
cd ${PROJECT_DIR}
rm -rf corpus crashes target ${CARGO_TARGET_DIR} difuzz difuzz_target_* Cargo.lock ets.toml fuzzer.log target.log .cur_input* /difuzz/dwfl-core
pkill difuzz_ || true
'''

[tasks.all]
linux_alias = "all_unix"
mac_alias = "all_unix"
windows_alias = "unsupported"

[tasks.all_unix]
dependencies = ["target", "casr", "coverage", "debug"]
