# Variables
[env]
PROJECT_DIR = { script = ["pwd"], condition = { env_not_set = ["PROJECT_DIR"] } }
EXAMPLE_DIR = { value = "${PROJECT_DIR}" }
DIFUZZ_DIR = { value = "/directed_target/sydr/difuzz", condition = { env_not_set = ["DIFUZZ_DIR"] } }
DIFUZZ_DIR_ABS = { script = ["realpath ${DIFUZZ_DIR}"] }
OUT_DIR = { value = "${PROJECT_DIR}", condition = { env_not_set = ["OUT_DIR"] } }
OUT_DIR_ABS = { script = ["realpath ${OUT_DIR}"] }
DIFUZZ_ARGS = { value = "-r main --weights reverse -o difuzz -j8 --analyse-icalls strong", condition = { env_not_set = ["DIFUZZ_ARGS"] } }
CARGO_TARGET_DIR = { value = "${PROJECT_DIR}/target", condition = { env_not_set = [
  "CARGO_TARGET_DIR",
] } }
PROFILE = { value = "release", condition = { env_not_set = ["PROFILE"] } }
LIBAFL_CC = '${DIFUZZ_DIR_ABS}/libafl_cc'
LIBAFL_CXX = '${DIFUZZ_DIR_ABS}/libafl_cxx'
FUZZER = '${DIFUZZ_DIR_ABS}/libafl_difuzz'
ETS_SHARED_MANAGER = '${DIFUZZ_DIR_ABS}/ETSSharedManager'
TARGET = '${OUT_DIR_ABS}/difuzz_target_deep'

[tasks.unsupported]
script_runner = "@shell"
script = '''
echo "Cargo-make not integrated yet on this"
'''

[tasks.debug]
linux_alias = "debug_unix"
mac_alias = "debug_unix"
windows_alias = "unsupported"

[tasks.debug_unix]
script_runner = "@shell"
script = '''
cd ${PROJECT_DIR}
export LLVM_COMPILER=clang
export CC=clang; export CXX=clang++
$CC -g deep.c -o deep
$CC -g deep_checksum.c -o deep_checksum
$CC -g deep_mixed.c -o deep_mixed
mv ${PROJECT_DIR}/deep ${OUT_DIR_ABS}/debug_deep
mv ${PROJECT_DIR}/deep_checksum ${OUT_DIR_ABS}/debug_deep_checksum
mv ${PROJECT_DIR}/deep_mixed ${OUT_DIR_ABS}/debug_deep_mixed
'''

[tasks.coverage]
linux_alias = "coverage_unix"
mac_alias = "coverage_unix"
windows_alias = "unsupported"

[tasks.coverage_unix]
script_runner = "@shell"
script = '''
cd ${PROJECT_DIR}
export LLVM_COMPILER=clang
export CC=clang; export CXX=clang++

python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py --sig -a insert -l c -f deep.c
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py --sig -a insert -l c -f deep_checksum.c
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py --sig -a insert -l c -f deep_mixed.c

$CC -g -fprofile-instr-generate -fcoverage-mapping deep.c -o deep
$CC -g -fprofile-instr-generate -fcoverage-mapping deep_checksum.c -o deep_checksum
$CC -g -fprofile-instr-generate -fcoverage-mapping deep_mixed.c -o deep_mixed

python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py --sig -a remove -l c -f deep.c
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py --sig -a remove -l c -f deep_checksum.c
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py --sig -a remove -l c -f deep_mixed.c

mv ${PROJECT_DIR}/deep ${OUT_DIR_ABS}/coverage_deep
mv ${PROJECT_DIR}/deep_checksum ${OUT_DIR_ABS}/coverage_deep_checksum
mv ${PROJECT_DIR}/deep_mixed ${OUT_DIR_ABS}/coverage_deep_mixed
'''

[tasks.difuzz]
linux_alias = "difuzz_unix"
mac_alias = "difuzz_unix"
windows_alias = "unsupported"

[tasks.difuzz_unix]
script_runner = "@shell"
script = '''
cd ${PROJECT_DIR}
export LLVM_COMPILER=clang
export CC=wllvm; export CXX=wllvm++

python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a insert -l c -f deep.c
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a comment -l c -f deep.c
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a insert -l c -f deep_checksum.c
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a comment -l c -f deep_checksum.c
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a insert -l c -f deep_mixed.c
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a comment -l c -f deep_mixed.c

$CC -g deep.c -o deep
$CC -g deep_checksum.c -o deep_checksum
$CC -g deep_mixed.c -o deep_mixed

cd ${OUT_DIR_ABS}
${DIFUZZ_DIR_ABS}/difuzz -c ${PROJECT_DIR}/config.toml -b ${PROJECT_DIR}/deep -e ${OUT_DIR_ABS}/ets.toml ${DIFUZZ_ARGS}
${DIFUZZ_DIR_ABS}/difuzz -c ${PROJECT_DIR}/config_checksum.toml -b ${PROJECT_DIR}/deep_checksum -e ${OUT_DIR_ABS}/ets_checksum.toml ${DIFUZZ_ARGS}
${DIFUZZ_DIR_ABS}/difuzz -c ${PROJECT_DIR}/config_mixed.toml -b ${PROJECT_DIR}/deep_mixed -e ${OUT_DIR_ABS}/ets_mixed.toml ${DIFUZZ_ARGS}
'''

[tasks.target]
linux_alias = "target_unix"
mac_alias = "target_unix"
windows_alias = "unsupported"

[tasks.target_unix]
script_runner = "@shell"
script = '''
cd ${PROJECT_DIR}
export CC=${LIBAFL_CC}
export CXX=${LIBAFL_CXX}

export LIBAFL_SHARED_NAME="deep"
${ETS_SHARED_MANAGER} -a remove -n ${LIBAFL_SHARED_NAME}
${ETS_SHARED_MANAGER} -a create -n ${LIBAFL_SHARED_NAME}
${ETS_SHARED_MANAGER} -a parse -n ${LIBAFL_SHARED_NAME} -i ${OUT_DIR_ABS}/ets.toml
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a uncomment -l c -f deep.c
$CC -g deep.c -o deep
${ETS_SHARED_MANAGER} -a dump -n ${LIBAFL_SHARED_NAME} -o ${OUT_DIR_ABS}/ets.toml
${ETS_SHARED_MANAGER} -a remove -n ${LIBAFL_SHARED_NAME}
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a remove -l c -f deep.c
mv ${PROJECT_DIR}/deep ${TARGET}

export LIBAFL_SHARED_NAME="deep_checksum"
${ETS_SHARED_MANAGER} -a remove -n ${LIBAFL_SHARED_NAME}
${ETS_SHARED_MANAGER} -a create -n ${LIBAFL_SHARED_NAME}
${ETS_SHARED_MANAGER} -a parse -n ${LIBAFL_SHARED_NAME} -i ${OUT_DIR_ABS}/ets_checksum.toml
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a uncomment -l c -f deep_checksum.c
$CC -g deep_checksum.c -o deep_checksum
${ETS_SHARED_MANAGER} -a dump -n ${LIBAFL_SHARED_NAME} -o ${OUT_DIR_ABS}/ets_checksum.toml
${ETS_SHARED_MANAGER} -a remove -n ${LIBAFL_SHARED_NAME}
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a remove -l c -f deep_checksum.c
mv ${PROJECT_DIR}/deep_checksum ${TARGET}_checksum

export LIBAFL_SHARED_NAME="deep_mixed"
${ETS_SHARED_MANAGER} -a remove -n ${LIBAFL_SHARED_NAME}
${ETS_SHARED_MANAGER} -a create -n ${LIBAFL_SHARED_NAME}
${ETS_SHARED_MANAGER} -a parse -n ${LIBAFL_SHARED_NAME} -i ${OUT_DIR_ABS}/ets_mixed.toml
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a uncomment -l c -f deep_mixed.c
$CC -g deep_mixed.c -o deep_mixed
${ETS_SHARED_MANAGER} -a dump -n ${LIBAFL_SHARED_NAME} -o ${OUT_DIR_ABS}/ets_mixed.toml
${ETS_SHARED_MANAGER} -a remove -n ${LIBAFL_SHARED_NAME}
python3 ${DIFUZZ_DIR_ABS}/insert_forkserver.py -a remove -l c -f deep_mixed.c
mv ${PROJECT_DIR}/deep_mixed ${TARGET}_mixed
'''
dependencies = ["difuzz"]

# Run the fuzzer
[tasks.run]
linux_alias = "run_unix"
mac_alias = "run_unix"
windows_alias = "unsupported"

[tasks.run_unix]
script_runner = "@shell"
script = '''
LIBAFL_DEBUG_OUTPUT=1 ${FUZZER} -- ${TARGET}
'''
dependencies = ["target"]

# Clean all built artifacts
[tasks.cleanall]
script_runner = "@shell"
script = '''
cd ${PROJECT_DIR}
rm -rf corpus crashes target ${CARGO_TARGET_DIR} difuzz_target_* debug_* coverage_* Cargo.lock ets.toml ETSSharedManager* fuzzer.log target.log .cur_input* difuzz difuzz_fuzzer_* deep_checksum deep_mixed deep .deep*
git restore -- deep.c deep_checksum.c deep_mixed.c
pkill difuzz_ || true
'''

[tasks.all]
linux_alias = "all_unix"
mac_alias = "all_unix"
windows_alias = "unsupported"

[tasks.all_unix]
dependencies = ["target", "debug", "coverage"]
